services:
  nestjs_test_app:
    container_name: 'nestjs_test_app'
    build: ./nestjs_test_app/
    ports:
      - "3000:3000"
    command: npm run start:dev

  run_tests:
    container_name: pytest
    build: .
    volumes:
      - '../:/var/www/tests'
    depends_on:
      - nestjs_test_app
    command: >
       bash -c "
         poetry install &&
         poetry run pytest
       "
