name: Run Tests

run-name: ${{ github.actor }} is executing tests
on:
  workflow_dispatch:
    inputs:
      chosen-os:
        required: true
        type: choice
        options:
          - ubuntu-latest
          - macos-latest

jobs:
  start_app_and_run_tests:
    runs-on: ["${{ inputs.chosen-os }}"]
    steps:
      - name: Checkout️
        uses: actions/checkout@v4
      - run: cd .docker && docker compose up -d
      - run: docker wait pytest
      - run: docker compose down
